### ISSUE TITLE
Sabnzbd

### ISSUE THREAD

**Issue by arcidodo** [evilmarty/hassio-addons#8]
when i start the sabnzbd addon i get this error:

s6-overlay-suexec: fatal: can only run as pid 1

**Comment by evilmarty** [comment]
I am aware of the issue. I personally downgraded to the previous version as I haven't had time to investigate.

**Comment by evilmarty** [comment]
I took a quick look and managed to fix the issue. This was apparently caused by [v3 of S6 which is enforcing that it be PID 1](https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/). A quick change to the add-on config appears to have resolved this. If you have updated to the latest version you will need to re-install the add-on. Be sure to **back up your data** before you do it or it will be deleted when you uninstall!
